### ISSUE TITLE
Unknown text box popping up when downloading a game?

### ISSUE THREAD

**Issue by rguzgasr** [CarrotRub/Fitgirl-Repack-Launcher#4]
So, whenever I want to install a game (for this instance Outlast 2), a text box appears before the download "starts". I type something random to it, the download quote starts unquote, but it actually doesn't start, there is no data transfer and time remaining is infinity years. Is this intended, or a bug? 

![image](https://github.com/CarrotRub/Fitgirl-Repack-Launcher/assets/66805881/84cd5c1c-c8da-4216-8925-89eb1d4c8b19)
![image](https://github.com/CarrotRub/Fitgirl-Repack-Launcher/assets/66805881/ed255784-3936-499b-84f0-80dcf7fe8588)
![image](https://github.com/CarrotRub/Fitgirl-Repack-Launcher/assets/66805881/df3ff80d-2b01-424e-a93b-476fb335d8ca)

**Comment by carlossclaro** [comment]
I believe you have a old build as I can see the old UI. Can you try doing a git pull to pull all changes and let me know if it's still the same issue?

@rguzgasr

**Comment by CarrotRub** [comment]
Fixed, he just didn't do the update.
